### ISSUE TITLE
发现网站加载速度比较慢，好像是谷歌字体的原因，求怎么解决

### ISSUE THREAD

**Issue by yuetian12** [mmmwhy/ss-panel-and-ss-py-mu#11]
网上搜了一圈，大概解决方案是删除或注释掉 font.googleapis.com 的那条css或web字体格式化，或者用360的cdn，不过用360的解决方案好像要备案。。。那么剩下两条解决方案我不知道怎么实施呀0-0，网上都是wordpress的方案

**Comment by mmmwhy** [comment]
我擦嘞。。还真是诶，因为之前是解析到国内的，现在不知道为什么的。。。真蛋疼，我换成我科的源吧。

**Comment by mmmwhy** [comment]
https://fonts.googleapis.com/
你把域名写错了，目前来看解析很好呀。。。不知道你纠结什么呢....
![](https://cdn.mmmxcc.cn/blog/171101/6HKAEgl5j5.png)
