### ISSUE TITLE
安装成功后登陆提示错误：500

### ISSUE THREAD

**Issue by murazi** [mmmwhy/ss-panel-and-ss-py-mu#2]
出错了!
发生错误：500

安装过程中出现部分红字：
>
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libsse2.la
  CCLD     libssse3.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libsodium.la
<

> Checking ...
Nginx: OK
Error: MySQL install failed.
PHP: OK
PHP-FPM: OK
Sorry, Failed to install LNMP!
Please visit http://bbs.vpser.net/forum-25-1.html feedback errors and logs.
You can download /root/lnmp-install.log from your server,and upload lnmp-install.log to LNMP Forum.
Cloning into '/home/wwwroot/default'...
<

**Comment by murazi** [comment]
可最后的确提示安装成功了

#############################################################
# 安装成功，登录XXX看看吧~                  #
# Github: https://github.com/mmmwhy/ss-panel-and-ss-py-mu   #
# Author: Feiyang.li                                        #
# Blog: http://feiyang.li/2017/05/09/ss-shell/index.html    #
#############################################################

**Comment by mmmwhy** [comment]
红字部分不影响使用，你提到的500错误。php任何错误都是500，所以你提供的信息有点少，没办法帮你判断。

**Comment by murazi** [comment]
我再安装一次试试，怎么加你联系方式，我提供给你log

**Comment by murazi** [comment]
这次新安装的版本，访问首页出现404了
