### ISSUE TITLE
是否可以支持IPV6呢？

### ISSUE THREAD

**Issue by luzhengyang1995** [mmmwhy/ss-panel-and-ss-py-mu#3]
尝试了一下，不知道怎样支持IPV6。

**Comment by mmmwhy** [comment]
因为我没有ipv6环境，没法测试，所以我也不太清楚。

**Comment by edboffical** [comment]
https://github.com/edboffical/bsp/

**Comment by mmmwhy** [comment]
@luzhengyang1995  经过测试，脚本支持ipv6，新建节点链接填ipv6地址就好。

**Comment by bigrain1993** [comment]
有没有办法双栈？一个链接填v6一个链接填v4?
