### ISSUE TITLE
两个脚本二选一，还是都要装？

### ISSUE THREAD

**Issue by bi-kai** [mmmwhy/ss-panel-and-ss-py-mu#34]
ss-panel mod魔改版一键脚本
ss-panel v3一键脚本

两个脚本二选一，还是都要装？

**Comment by MAOGE2018** [comment]
选一个吧！

**Comment by bi-kai** [comment]
@MAOGE2018 推荐用哪个呢？

**Comment by mmmwhy** [comment]
这是两个脚本，请理解sspanel v3和sspanel魔改版是两个系统。
