### ISSUE TITLE
最近都有这个问题，请问怎么解决啊，大神？

### ISSUE THREAD

**Issue by AIDE741500926** [mmmwhy/ss-panel-and-ss-py-mu#37]
失败: Unable to resolve host "www.google.com".
No address associated with hostname

{
    "server": "域名隐藏了",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "timeout": 300,
    "workers": 1,
    "server_port": 8888,
    "password": "密码隐藏了",
    "method": "aes-256-cfb",
    "obfs": "plain",
    "obfs_param": "",
    "protocol": "origin",
    "protocol_param": ""
}

什么问题啊？
电脑可以上网，手机不可以，手机连上没网！

**Comment by mmmwhy** [comment]
这个问题跟我这边没关系吧。。。。

我只能说服务正常使用，至于有的网络能用有的网络不能用。。。

这。。。
