### ISSUE TITLE
错误信息bash: ss-panel-v3-mod.sh: No such file or directory

### ISSUE THREAD

**Issue by feng99** [mmmwhy/ss-panel-and-ss-py-mu#38]
每次都卡在这个地方  
![image](https://user-images.githubusercontent.com/13182572/40400361-563eb90e-5e74-11e8-8ee0-8f3adc4967f1.png)

再次运行会提示 lnmp已经安装请先卸载.

执行命令为:/bin/sh ss-panel-v3-mod.sh

**Comment by wzyonggege** [comment]
同样的问题，请问你结局了吗

**Comment by mmmwhy** [comment]
退出来，自己  bash ss-panel-v3-mod.sh 1
