### ISSUE TITLE
似乎无法关闭SS后台？

### ISSUE THREAD

**Issue by ForeverOpp** [mmmwhy/ss-panel-and-ss-py-mu#39]
无论直接kill掉python进程亦或者运行/root/shadowsocks目录下的stop.sh均无法停止后台，请问如何停止SS后台？

**Comment by lsk008** [comment]
这个程序用守护进程运行的，supervisorctl stop

**Comment by ForeverOpp** [comment]
![image](https://user-images.githubusercontent.com/9302540/40839076-7c02f176-65d3-11e8-9748-3ed63d37061e.png)
已经停止，但是网页面板的对接仍然显示在线。

**Comment by ForeverOpp** [comment]
成功了，感谢。
