### ISSUE TITLE
RuntimeException HELP App\Controllers\AdminController:sysinfo is not resolvable

### ISSUE THREAD

**Issue by Arghs** [mmmwhy/ss-panel-and-ss-py-mu#4]
Getting this error: 

> RuntimeException
> HELP
> App\Controllers\AdminController:sysinfo is not resolvable
> Open: /home/wwwroot/default/vendor/slim/slim/Slim/CallableResolver.php
>                     }
>                     $resolved = new $class($this->container);
>                 }
>             }
>         }
>  
>         if (!is_callable($resolved)) {
>             throw new RuntimeException(sprintf('%s is not resolvable', $toResolve));
>         }
>  

whenever I try to open "系统维护"

running Centos 7 sspanel
I also sent you an email, check that if you got time.

**Comment by Arghs** [comment]
Thanks but no thanks

**Comment by viRikaRe** [comment]
Maybe you're using ss-panel v3.4.6 . Then try adding following lines to `app/Controllers/AdminController.php`:

    public function sysinfo($request, $response, $args)
    {
        return $this->view()->display('admin/sys.tpl');
    }

These lines are copied from latest commits of ss-panel, which fixes the problem.
