### ISSUE TITLE
有极其严重的漏洞

### ISSUE THREAD

**Issue by tony-sunjian** [mmmwhy/ss-panel-and-ss-py-mu#47]
http://主机的ip/mu/users?key=mupass&node=1

能直接看到所有注册用户的账号和密码？什么鬼

**Comment by hklcf** [comment]
這是訂閱吧？

**Comment by mmmwhy** [comment]
@tony-sunjian  
可以把key理解为系统秘钥，默认是mupass，在.config内可修改。

**Comment by tony-sunjian** [comment]
好的，我修改了nginx配置，使得mu目录无法被外部ip访问
